name: Build and Upload to SquareCloud

on:
  workflow_call:
    secrets:
      SQUARE_API_KEY:
        description: "Square Cloud API Key"
        required: true
      API_ID_KEY:
        description: "Square Cloud App ID"
        required: true
      TOKEN:
        description: "Token para checkout do repositório chamador"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do repositório CHAMADOR (não do global)
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: caller-repo

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create dummy lock file
        run: echo "{}" > package-lock.json
        working-directory: ./caller-repo

      # 3. Instala dependências do chamador
      - name: Install dependencies
        run: npm install --no-package-lock
        working-directory: ./caller-repo
        
      - name: Clean cache
        run: |
          npm cache clean --force
          rm -rf node_modules/.cache          
        working-directory: ./caller-repo

      # 4. Build do projeto do chamador
      - name: Build project
        run: |
          export NODE_OPTIONS=--max-old-space-size=8192
          export GENERATE_SOURCEMAP=false
          CI=false npm run build
        working-directory: ./caller-repo

      # 5. Cria ZIP com os arquivos do chamador
      - name: Prepare zip from caller
        run: |
          cd caller-repo
          mkdir deploy
          cp package.json deploy/
          cp squarecloud.config deploy/
          cp -r build deploy/ || cp -r dist deploy/ || echo "Pasta build/dist não encontrada"
          cd deploy
          zip -r ../../app.zip .
          cd ../..

      # 6. Checkout do repositório GLOBAL (para pegar o script de deploy)
      - name: Checkout global repository
        uses: actions/checkout@v4
        with:
          repository: sheila-garcia-pro/pipeline-deploy
          token: ${{ secrets.TOKEN }}
          path: global-scripts


      # 5. Instala dependências globais
      - name: Install global dependencies
        run: |
          cd global-scripts
          npm install
          npm list @squarecloud/api

      # 6. Move o ZIP para o global-scripts
      - name: Move app.zip
        run: mv app.zip global-scripts/

      # 7. Executa o deploy
      - name: Run Square Cloud deployment
        run: |
          cd $GITHUB_WORKSPACE/global-scripts
          echo "1. Verificando instalação..."
          npm install
          echo "2. Testando importação do pacote..."
          npm run test
          echo "3. Procurando app.zip..."
          find . -name "app.zip" -exec ls -lh {} \; 
          echo "4. Copiando app.zip para o diretório correto..."
          # Tenta encontrar o arquivo em vários locais possíveis
          if [ -f ../app.zip ]; then
          cp ../app.zip src/
          elif [ -f app.zip ]; then
          cp app.zip src/
          elif [ -f $GITHUB_WORKSPACE/app.zip ]; then
          cp $GITHUB_WORKSPACE/app.zip src/
          else
          echo "❌ ERRO: app.zip não encontrado em nenhum local"
          exit 1
          fi
          echo "5. Verificando app.zip..."
          [ -f app.zip ] && echo "app.zip encontrado" || echo "ERRO: app.zip não encontrado"
          echo "6. Executando deploy..."
          node src/square-deploy.cjs
        env:
          SQUARE_API_KEY: ${{ secrets.SQUARE_API_KEY }}
          API_ID_KEY: ${{ secrets.API_ID_KEY }}
